### ISSUE TITLE
can't start webpack-dev-server

### ISSUE THREAD

**Issue by y-takey** [SokichiFujita/starter-react-flux#12]
Thanks for nice starter kit :)

I've got following error, when i run `yarn start`.
```
yarn run v1.3.2
$ webpack-dev-server -d --progress --colors
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
module.js:538
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xxx/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Becouse, [webpack v4 is released](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) at Feb 25.
I worked around this issue with older webpack and webpack-dev-server.
```
$ yarn remove webpack webpack-dev-server
$ yarn add -D webpack@3.11.0 webpack-dev-server@2.11.2
```

**Comment by sl2** [comment]
Thank you! I’v just updated starter-react-flux to support for webpack v4. Please upgrade your environment.

Current webpack config is almost same as v3. I’ll change it to v4 style with the next version

**Comment by SokichiFujita** [comment]
Thank you! I’v just updated starter-react-flux to support for webpack v4. Please upgrade your environment.

Current webpack config is almost same as v3. I’ll change it to v4 style with the next version

**Comment by SokichiFujita** [comment]
I also changed internal installation command from npm to yarn as you do. It will be faster than old version.

**Comment by y-takey** [comment]
Awesome 🎉  Thank you great work!
